# Generated by Django 4.1.2 on 2023-04-11 16:32

from django.db import migrations
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
    ]
